modLoader = "javafml"
loaderVersion = "${loader}"
license = "GPLv3"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
description = "Refactors Minecraft's music to be dynamic and reactive, including new fantasy and celtic tracks to give an air of adventure."
authors = "CircuitLord"
logoFile = "assets/reactivemusic/icon.png"
displayURL = "https://modrinth.com/mod/reactive-music"

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "${loader}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft}"
ordering = "NONE"
side = "CLIENT"
